version: '3.2'

services:
  php-apache:
    ports:
      - '80:80'
    networks:
      - test_network
    build: './docker/php'
    volumes:
      - .:/var/www/
    working_dir: /var/www
  mysql:
    ports:
      - '3306:3306'
    networks:
      - test_network
    build: './docker/mysql'
    environment:
      MYSQL_USER: 'john_doe'
      MYSQL_PASSWORD: 'e3f11506-8bbf-4511-938a-10cc2d42a3ca'
      MYSQL_ROOT_PASSWORD: 'f8b76cbf-d314-4907-9350-1a880444101d'
      MYSQL_DATABASE: 'planner'
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  test_network:
volumes:
  mysql_data:
